blog_posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog_posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^new$', views.post_create, name='post_new'),
    url(r'^edit/(?P<pk>\d+)$', views.post_update, name='post_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.post_delete, name='post_delete'),
]

crudapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib import admin
from blog_posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog_posts/', include('blog_posts.urls', namespace='blog_posts')),
    url(r'^$',views.post_list,name='post_list'),
    url(r'^$',views.post_list,name='post_create'),
    url(r'^$',views.post_list,name='post_update'),
    url(r'^$',views.post_list,name='post_delete'),
    url(r'^$',views.index,name='index'),
    url(r'^formpage/',views.form_name_view,name='form_name_view'),
]

blog_posts/models.py
from __future__ import unicode_literals
from django.db import models
from django.db import models
# Create your models here.
class blog_posts(models.Model):
    title = models.CharField(max_length=400)
    tag = models.CharField(max_length=50)
    author = models.CharField(max_length=120)

    def __unicode__(self):
        return self.title
    def get_post_url(self):
        return reverse('post_edit', kwargs={'pk': self.pk})



class Topic(models.Model):

    top_name=models.CharField(max_length=100,unique=True)

    def __str__(self):

        return self.top_name

class Webpage(models.Model):

    topic=models.ForeignKey(Topic)

    name=models.CharField(max_length=100,unique=True)

    url=models.URLField(unique=True)

    def __str__(self):

        return self.name

class AccessRecord(models.Model):

    name=models.ForeignKey(Webpage)

    date=models.DateField()

    def __str__(self):

        return str(self.date)

blog_posts/forms.py
from django import forms

class FormName(forms.Form):
    name=forms.CharField(max_length=30)
    email=forms.EmailField(max_length=50)
    text=forms.CharField(widget=forms.Textarea)

blog_posts/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from blog_posts.models import blog_posts
from . import forms
# Create your views here.
def index(request):
    return render(request,'blog_posts/index.html')


def form_name_view(request):
    form=forms.FormName()

    if request.method == 'POST':
        form=forms.FormName(request.POST)
        if form.is_valid():
            print("Hey this is successfully validation")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])
    return render(request,'blog_posts/form_page.html',{'form':form})



class PostsForm(ModelForm):
    class Meta:
        model = blog_posts
        fields = ['id', 'title', 'author']
def post_list(request, template_name='blog_posts/post_list.html'):
    posts = blog_posts.objects.all()
    data = {}
    data['object_list'] = posts
    return render(request, template_name, data)
def post_create(request, template_name='blog_posts/post_form.html'):
    form = PostsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})
def post_update(request, pk, template_name='blog_posts/post_form.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    form = PostsForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})
def post_delete(request, pk, template_name='blog_posts/post_delete.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    if request.method=='POST':
        post.delete()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'object': post})

templates/blog_posts/form_page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>FORMS TITLE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>>
<body>
<div class ="container">
    <form method="POST">
    {{ form.as_p}}
        {% csrf_token %}
    <input type= "submit" class="btn btn-primary", value="SUBMIT">
    </form>
</div>
</body>
</html>

templates/blog_posts/index.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
    <meta charset="UTF-8">
    <title>TITLE PAGE</title>
</head>
<body>
<h1>Here I am printing the blog</h1>
<img src="static/images/python.png" alt="OOps! wrong path">
</body>

</html>

templates/blog_posts/post_delete.html
<!DOCTYPE html>

<html>

  <head>

    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <title>Django CRUD application!</title>

  </head>

  <body>

    <div class="container">

      <form method="post">{% csrf_token %}

        Are you sure you want to delete "{{ object }}" ?

        <input class="btn btn-primary" type="submit" value="Submit" />

      </form>

    </div>

  </body>

</html>

templates/blog_posts/post_form.html
<!DOCTYPE html>

<html>

  <head>

    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <title>Django CRUD application!</title>

  </head>

  <body>

    <div class="container">

      <form  method="post">{% csrf_token %}

        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Submit" />

      </form>

    </div>

  </body>

</html>

templates/blog_posts/post_list.html
<!DOCTYPE html>

<html>

  <head>

    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <title>Django CRUD application!</title>

  </head>

  <body>

    <div class="container">

        <h1>Blog Posts</h1>

        <ul>

          {% for post in object_list %}

          <li><p>Post ID: <a href="{% url "blog_posts:post_edit" post.id %}">{{ post.id }}</a></p>

          <p>Title: {{ post.title }}</p>

            <a href="{% url "blog_posts:post_delete" post.id %}">Delete</a>

          </li>

          {% endfor %}

        </ul>



        <a href="{% url "blog_posts:post_new" %}">Click Here to Enter a New Blog</a>

    </div>

  </body>

</html>